name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
      - name: Run and collect coverage
        run: |
          coverage run --branch bms_sender/bms_sender_test.py
          coverage html -d bms_sender/htmlcov
          coverage run --branch bms_receiver/bms_stream_receiver_handler.test.py
          coverage html -d bms_receiver/htmlcov
      - name: Upload coverage for sender
        uses: actions/upload-artifact@v2
        with:
          name: sender coverage
          path: bms_sender/htmlcov
          retention-days: 1
      - name: Upload coverage for receiver
        uses: actions/upload-artifact@v2
        with:
          name: receiver coverage
          path: bms_receiver/htmlcov
          retention-days: 1
      - name: Run
        run: python bms_sender/bms_sender.py | python bms_receiver/bms_receiver.py
